# Generated by Django 3.0.6 on 2020-06-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=60)),
                ('had_eaten', models.BooleanField(default=False)),
                ('cook_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('res_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('foods_in_date', models.ManyToManyField(to='foods.food_date')),
            ],
        ),
        migrations.CreateModel(
            name='constructor',
            fields=[
                ('cons_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('restaurant_names', models.ManyToManyField(to='foods.restaurant')),
            ],
        ),
    ]
