# Generated by Django 3.0.6 on 2020-06-21 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_foodscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodscount',
            name='count',
        ),
    ]
