# Generated by Django 3.0.6 on 2020-06-21 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_remove_foodscount_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodscount',
            name='id',
        ),
        migrations.AlterField(
            model_name='foodscount',
            name='food',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='foods.food_date'),
        ),
    ]
